geoipDb: "/usr/share/GeoIP/GeoLite2-Country.mmdb"
useWhitelist: false
useBlacklist: false
kickMessage: "This server can only be connected to from authorized countries."
whitelist:
  - "LOOPBACK"
  - "PRIVATE"
blacklist:
  - "UNKNOWN"
  - "TESTNET"
  - "INTERNET"
  - "SHARED"
  - "SUBNET"
